// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkwpejsipgftkjcinneo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrd3BlanNpcGdmdGtqY2lubmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODIwNTYsImV4cCI6MjA1ODY1ODA1Nn0.egS4GlRoZ7MWs3t3f3_BSyYxcYgEzu9TeuMiZHcsjdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);